name: using_dio
description: Using Dio package.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^4.0.0-nullsafety.1
  get: ^4.1.4

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets: 
    - .env
